export const installBannerStyles = {
  root: {
    position: 'fixed',
    bottom: { xs: 'auto', sm: 'calc(16px + env(safe-area-inset-bottom))' },
    top: { xs: 'alc(16px + env(safe-area-inset-top))', sm: 'auto' },
    right: 16,
    zIndex: 'drawer',
    width: { xs: 'calc(100% - 32px)', sm: 400 },
    maxHeight:
      'calc(100dvh - 32px - env(safe-area-inset-top) - env(safe-area-inset-bottom))',
    overflowY: 'auto',
    p: { xs: 2, sm: 2.5 },
    borderRadius: 4,
    bgcolor: '#FFFDF5',
    color: '#173E29',
    border: '1px solid rgba(23,62,41,.14)',
  },
  close: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 40,
    height: 40,
    color: '#526158',
  },
  heading: {
    fontFamily: 'var(--font-display)',
    fontSize: 22,
    fontWeight: 700,
    lineHeight: 1.2,
  },
  description: {
    mt: 1.5,
    color: '#526158',
    fontSize: 14,
    lineHeight: 1.6,
  },
  button: {
    mt: 2,
    minHeight: 44,
    borderRadius: 2.5,
    bgcolor: '#173E29',
    color: '#FFFDF5',
    fontWeight: 700,
    textTransform: 'none',
    boxShadow: 'none',
    '&:hover': { bgcolor: '#245A3D', boxShadow: 'none' },
  },
  instructions: {
    mt: 2,
    p: 1.5,
    borderRadius: 2.5,
    bgcolor: '#EAF1E3',
    fontSize: 13,
    lineHeight: 1.6,
  },
} as const;
