/**
 * Font stacks of the design system. The `--font-display` and `--font-text`
 * variables are generated by `next/font` in
 * `src/shared/lib/fonts/fonts.constant.ts` and applied to the `<html>`
 * element; whatever follows each `var()` is the fallback used while the font
 * loads (`display: 'swap'`).
 *
 * `display` is the serif voice, reserved for titles (`h1`–`h6`). `text` is the
 * sans voice and the theme's `fontFamily`, applied to `body` by `CssBaseline`
 * and inherited by every other variant.
 */
export const fonts = {
  display: "var(--font-display), Georgia, 'Times New Roman', serif",
  text: 'var(--font-text), Arial, Helvetica, sans-serif',
} as const;
